# Generated by Django 3.0.7 on 2020-07-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mynote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=16, verbose_name='작성자')),
                ('class_id', models.CharField(max_length=16, verbose_name='강의아이디')),
                ('title', models.CharField(max_length=126, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('keyword', models.TextField(verbose_name='키워드')),
                ('summary', models.TextField(verbose_name='요악')),
            ],
        ),
    ]
