# Generated by Django 3.0.7 on 2020-07-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20200705_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynote',
            name='keyword4',
            field=models.CharField(max_length=12, null=True, verbose_name='키워드4'),
        ),
        migrations.AddField(
            model_name='mynote',
            name='keyword5',
            field=models.CharField(max_length=12, null=True, verbose_name='키워드5'),
        ),
    ]
